services:
  app:
    build:
      context: ../..
      dockerfile: production/node/Dockerfile
      target: runtime
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    init: true
    restart: "no"
